# Generated by Django 5.2.1 on 2025-05-27 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognize', '0002_alter_recognitionresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionresult',
            name='confidence',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
