# Generated by Django 5.2.1 on 2025-05-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognize', '0003_alter_recognitionresult_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognitionresult',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='recognitionresult',
            name='image_recog_result__726103_idx',
        ),
        migrations.RemoveIndex(
            model_name='recognitionresult',
            name='image_recog_image_i_ac1485_idx',
        ),
        migrations.RemoveField(
            model_name='imagerecognition',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='imagerecognition',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='result_type',
        ),
        migrations.AlterField(
            model_name='recognitionresult',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recognitionresult',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
